FORMAT: 1A
HOST: https://bloodflow.herokuapp.com/api

# Bloodflow API 


# Group Users
Работа с пользователями

## Users Collection [/users]
### Получение списка пользователей[GET]
+ Response 200 (application/json)

    [
        {
            "firstName": "Иванов",
            "secondName": "Иван",
            "lastName": "Иванович",
            "city": "Днепропетровск",
            "phone": "+380661234567",
            "email": "demo@gmail.com",
            "blood": 3,
            "rhesus": "+",
            "ready": true,
            "_id": "54be9f25d86a515e79dfb8fa",
            "__v": 0
        }
    ]
### Создание пользователя [POST]
+ Request (application/json)

        { 
            "firstName": "Иванов", 
            "secondName": "Иван", 
            "lastName":"Иванович",
            "city": "Днепропетровск", 
            "phone":"+380661234567", 
            "email":"demo@gmail.com", 
            "blood":3, 
            "rhesus":"+",
            "ready":true
        }

+ Response 200 (application/json)

        {
            "__v": 0,
            "firstName": "Иванов",
            "secondName": "Иван",
            "lastName": "Иванович",
            "city": "Днепропетровск",
            "phone": "+380661234567",
            "email": "demo@gmail.com",
            "blood": 3,
            "rhesus": "+",
            "ready": true,
            "_id": "54be9f25d86a515e79dfb8fa"
        }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
